In [1]:
import pandas as pd
import json

In [2]:
data = "../data/raw/timeRange_🔴 LIVE  KNOCKOUT STAGE HARI 5  M7 World Championship  (ID)_1769316629.5135531.json"

df_data = pd.read_json(data)
df_data.head()

,message_type,occurence_timestamp,timeStampUTC,author,content
0,Chat Message,3:25:30,2026-01-24 10:50:55.099409,@yamin12345-z,"{'message': '#7 ', 'emoji': [], 'text_content'..."
1,Chat Message,3:25:30,2026-01-24 10:50:55.222274,@fdoniaquilani9902,"{'message': 'Suport Indo ', 'emoji': [], 'text..."
2,Chat Message,3:25:30,2026-01-24 10:50:55.256967,@theycalledmeamadman2772,"{'message': 'ONIC MANA BISA ', 'emoji': [], 't..."
3,Chat Message,3:25:30,2026-01-24 10:50:55.363708,@loveydumpies,"{'message': 'AE plss ', 'emoji': [], 'text_con..."
4,Chat Message,3:25:30,2026-01-24 10:50:55.592918,@Amrik199,"{'message': 'hina AE biar menang terus ', 'emo..."

In [6]:
df_data['message'] = df_data['content'].apply(lambda x: x['message'])
df_data['emoji'] = df_data['content'].apply(lambda x: x['emoji'])
df_data['text_content'] = df_data['content'].apply(lambda x: x['text_content'])

In [12]:
df_data.head(20)

,message_type,occurence_timestamp,timeStampUTC,author,content,message,emoji,text_content
0,Chat Message,3:25:30,2026-01-24 10:50:55.099409,@yamin12345-z,"{'message': '#7 ', 'emoji': [], 'text_content'...",#7,[],#7
1,Chat Message,3:25:30,2026-01-24 10:50:55.222274,@fdoniaquilani9902,"{'message': 'Suport Indo ', 'emoji': [], 'text...",Suport Indo,[],Suport Indo
2,Chat Message,3:25:30,2026-01-24 10:50:55.256967,@theycalledmeamadman2772,"{'message': 'ONIC MANA BISA ', 'emoji': [], 't...",ONIC MANA BISA,[],ONIC MANA BISA
3,Chat Message,3:25:30,2026-01-24 10:50:55.363708,@loveydumpies,"{'message': 'AE plss ', 'emoji': [], 'text_con...",AE plss,[],AE plss
4,Chat Message,3:25:30,2026-01-24 10:50:55.592918,@Amrik199,"{'message': 'hina AE biar menang terus ', 'emo...",hina AE biar menang terus,[],hina AE biar menang terus
5,Chat Message,3:25:30,2026-01-24 10:50:55.658330,@reyhanpradesa,"{'message': 'bab1 ', 'emoji': [], 'text_conten...",bab1,[],bab1
6,Chat Message,3:25:30,2026-01-24 10:50:55.786273,@vegapratama-m7r,"{'message': 'JANGAN KALAH DRAF BROO ', 'emoji'...",JANGAN KALAH DRAF BROO,[],JANGAN KALAH DRAF BROO
7,Chat Message,3:25:30,2026-01-24 10:50:55.921605,@RaikenAdiguna,"{'message': 'JANGAN PUJI AE GUYS, PASIF NYA NY...","JANGAN PUJI AE GUYS, PASIF NYA NYALA",[],"JANGAN PUJI AE GUYS, PASIF NYA NYALA"
8,Chat Message,3:25:31,2026-01-24 10:50:55.933866,@fajarrr.01,"{'message': 'Yok AE ukir sejarah ', 'emoji': [...",Yok AE ukir sejarah,[],Yok AE ukir sejarah
9,Chat Message,3:25:31,2026-01-24 10:50:56.262834,@syahrulramadhan3178,"{'message': 'BISMILLAH AE MENANG ', 'emoji': [...",BISMILLAH AE MENANG,[],BISMILLAH AE MENANG
10,Chat Message,3:25:31,2026-01-24 10:50:56.246570,@dpaadly,"{'message': 'TL ', 'emoji': [], 'text_content'...",TL,[],TL
11,Chat Message,3:25:31,2026-01-24 10:50:56.291638,@danielar8655,"{'message': 'ae kasih tau siapa yang sampah ',...",ae kasih tau siapa yang sampah,[],ae kasih tau siapa yang sampah
12,Chat Message,3:25:31,2026-01-24 10:50:56.457452,@secretmistis7376,"{'message': 'bismillah AE yokkk $🤲 $🤲 $🤲 ', '...",bismillah AE yokkk $🤲 $🤲 $🤲,"[{'name': '🤲', 'isCustom': False, 'imageUrl': ...",bismillah AE yokkk
13,Chat Message,3:25:31,2026-01-24 10:50:56.515511,@TesalonikaTanda-n2c2c,"{'message': 'Gogo ae ', 'emoji': [], 'text_con...",Gogo ae,[],Gogo ae
14,Chat Message,3:25:31,2026-01-24 10:50:56.601617,@romarama1983,{'message': 'NGEHUJAT TEROS KALIAN BANTU SUPOR...,NGEHUJAT TEROS KALIAN BANTU SUPORT KE ALTER EG...,[],NGEHUJAT TEROS KALIAN BANTU SUPORT KE ALTER EG...
15,Chat Message,3:25:31,2026-01-24 10:50:56.769381,@iqbal_maulanaa,"{'message': 'BISMILLAH AE LETS GO ', 'emoji': ...",BISMILLAH AE LETS GO,[],BISMILLAH AE LETS GO
16,Chat Message,3:25:31,2026-01-24 10:50:56.717328,@Camping.busman,"{'message': 'AE pulang ', 'emoji': [], 'text_c...",AE pulang,[],AE pulang
17,Chat Message,3:25:31,2026-01-24 10:50:56.836177,@evosraider969,{'message': 'ASSALAMUALAIKUM WARAHMATULLAHI WA...,ASSALAMUALAIKUM WARAHMATULLAHI WABARAKATUH SAA...,"[{'name': '🙏', 'isCustom': False, 'imageUrl': ...",ASSALAMUALAIKUM WARAHMATULLAHI WABARAKATUH SAA...
18,Chat Message,3:25:31,2026-01-24 10:50:56.857872,@putriflorian3281,"{'message': 'pulang kah ini? ', 'emoji': [], '...",pulang kah ini?,[],pulang kah ini?
19,Chat Message,3:25:31,2026-01-24 10:50:56.777527,@warungmizan,"{'message': 'ppa awtis ', 'emoji': [], 'text_c...",ppa awtis,[],ppa awtis

In [11]:
df_data.to_csv("../data/processed/processed_data.csv", index=False)